services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgres-ngevent
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
      - ./internal/migrations/0001_init.up.sql:/docker-entrypoint-initdb.d/001_init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    image: redis:8.2.3
    container_name: redis-ngevent
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: ngevent-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./storage/profiles:/app/storage/profiles
      - ./storage/npwp:/app/storage/npwp
      - ./storage/nib:/app/storage/nib
      - ./storage/npwp/stage:/app/storage/npwp/stage
      - ./storage/nib/stage:/app/storage/nib/stage
      - ./storage/event/banner:/app/storage/event/banner
      - ./storage/updated/banner:/app/storage/updated/banner

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: ngevent-worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: [ "./worker" ]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: ngevent-frontend
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 5173:5173

volumes:
  psql_volume_bp:
